### ISSUE TITLE
Version 1.1 TODO

### ISSUE THREAD

**Issue by AlexanderEggers** [Mordag/hitogo#5]
- [x] Add support for AndroidX.
- [x] Improve POM creation.
- [x] Switch to Azure Pipeline CI.
